name: FoodDeli
description: "Application for food delivery"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_lints: ^2.0.0
  cached_network_image: ^3.2.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/products/
    - assets/icons/
    - assets/fonts/bmdaniel/
    - assets/fonts/inter/

  fonts:
    - family: bmdaniel
      fonts:
        - asset: assets/fonts/bmdaniel/bmdaniel_bold.ttf
    - family: inter_regular
      fonts:
        - asset: assets/fonts/inter/inter_regular.ttf
    - family: inter_light
      fonts:
        - asset: assets/fonts/inter/inter_light.ttf


